version: "3.9"
services:
  frontend:
    image: 370312947008.dkr.ecr.us-east-1.amazonaws.com/frontend:0.0.8
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - todo
      - login
  login:
    image:
    container_name: login
    depends_on:
      - users
  users:
     image:
     container_name: users
  todo:
    image:
    container_name: todo
    depends_on:
      - redis
  redis:
    image: redis
    container_name: